# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mdlidar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mdlidar.proto',
  package='mdlidar',
  syntax='proto3',
  serialized_pb=_b('\n\rmdlidar.proto\x12\x07mdlidar\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"=\n\x0bOrientation\x12\x1f\n\x04\x61xis\x18\x01 \x01(\x0b\x32\x11.mdlidar.Vector3D\x12\r\n\x05\x61ngle\x18\x02 \x01(\x02\"\xab\x01\n\x05State\x12#\n\x08position\x18\x01 \x01(\x0b\x32\x11.mdlidar.Vector3D\x12)\n\x0borientation\x18\x02 \x01(\x0b\x32\x14.mdlidar.Orientation\x12%\n\nposition_p\x18\x03 \x01(\x0b\x32\x11.mdlidar.Vector3D\x12+\n\rorientation_p\x18\x04 \x01(\x0b\x32\x14.mdlidar.Orientation\"L\n\x05Point\x12\r\n\x05range\x18\x01 \x01(\x02\x12\x10\n\x08rotation\x18\x02 \x01(\x02\x12\x11\n\tobject_id\x18\x03 \x01(\x05\x12\x0f\n\x07\x64ynamic\x18\x04 \x01(\x08\"\x92\x01\n\x05\x46rame\x12\x12\n\nstart_time\x18\x01 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03\x12\x1e\n\x06points\x18\x03 \x03(\x0b\x32\x0e.mdlidar.Point\x12\x1d\n\x05state\x18\x04 \x01(\x0b\x32\x0e.mdlidar.State\x12$\n\x0cobject_state\x18\x05 \x03(\x0b\x32\x0e.mdlidar.State\"i\n\x06Header\x12\x12\n\nobject_ids\x18\x01 \x03(\r\x12\x12\n\ndelta_time\x18\x02 \x01(\x02\x12\x16\n\x0e\x63hannels_count\x18\x03 \x01(\x05\x12\x1f\n\x17points_count_by_channel\x18\x04 \x01(\rB\x03\xf8\x01\x01\x62\x06proto3')
)




_VECTOR3D = _descriptor.Descriptor(
  name='Vector3D',
  full_name='mdlidar.Vector3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mdlidar.Vector3D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='mdlidar.Vector3D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='mdlidar.Vector3D.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=69,
)


_ORIENTATION = _descriptor.Descriptor(
  name='Orientation',
  full_name='mdlidar.Orientation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis', full_name='mdlidar.Orientation.axis', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angle', full_name='mdlidar.Orientation.angle', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=132,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='mdlidar.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='mdlidar.State.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='mdlidar.State.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_p', full_name='mdlidar.State.position_p', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation_p', full_name='mdlidar.State.orientation_p', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=306,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='mdlidar.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='range', full_name='mdlidar.Point.range', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='mdlidar.Point.rotation', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_id', full_name='mdlidar.Point.object_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dynamic', full_name='mdlidar.Point.dynamic', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=384,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='mdlidar.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='mdlidar.Frame.start_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='mdlidar.Frame.end_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points', full_name='mdlidar.Frame.points', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='mdlidar.Frame.state', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_state', full_name='mdlidar.Frame.object_state', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=533,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='mdlidar.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_ids', full_name='mdlidar.Header.object_ids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta_time', full_name='mdlidar.Header.delta_time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channels_count', full_name='mdlidar.Header.channels_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points_count_by_channel', full_name='mdlidar.Header.points_count_by_channel', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=640,
)

_ORIENTATION.fields_by_name['axis'].message_type = _VECTOR3D
_STATE.fields_by_name['position'].message_type = _VECTOR3D
_STATE.fields_by_name['orientation'].message_type = _ORIENTATION
_STATE.fields_by_name['position_p'].message_type = _VECTOR3D
_STATE.fields_by_name['orientation_p'].message_type = _ORIENTATION
_FRAME.fields_by_name['points'].message_type = _POINT
_FRAME.fields_by_name['state'].message_type = _STATE
_FRAME.fields_by_name['object_state'].message_type = _STATE
DESCRIPTOR.message_types_by_name['Vector3D'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['Orientation'] = _ORIENTATION
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3D = _reflection.GeneratedProtocolMessageType('Vector3D', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3D,
  __module__ = 'mdlidar_pb2'
  # @@protoc_insertion_point(class_scope:mdlidar.Vector3D)
  ))
_sym_db.RegisterMessage(Vector3D)

Orientation = _reflection.GeneratedProtocolMessageType('Orientation', (_message.Message,), dict(
  DESCRIPTOR = _ORIENTATION,
  __module__ = 'mdlidar_pb2'
  # @@protoc_insertion_point(class_scope:mdlidar.Orientation)
  ))
_sym_db.RegisterMessage(Orientation)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
  DESCRIPTOR = _STATE,
  __module__ = 'mdlidar_pb2'
  # @@protoc_insertion_point(class_scope:mdlidar.State)
  ))
_sym_db.RegisterMessage(State)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'mdlidar_pb2'
  # @@protoc_insertion_point(class_scope:mdlidar.Point)
  ))
_sym_db.RegisterMessage(Point)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
  DESCRIPTOR = _FRAME,
  __module__ = 'mdlidar_pb2'
  # @@protoc_insertion_point(class_scope:mdlidar.Frame)
  ))
_sym_db.RegisterMessage(Frame)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'mdlidar_pb2'
  # @@protoc_insertion_point(class_scope:mdlidar.Header)
  ))
_sym_db.RegisterMessage(Header)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\370\001\001'))
# @@protoc_insertion_point(module_scope)
